# Videogame
# el camino en diferentes mundos (razas de Bleach)
print("Eres una persona común y corriente en un día perfecto para salir, o éso es lo que aparenta,")
print("Sales de tu casa para pasear un rato al aire libre...")
print("Pasa el tiempo, se está haciendo de noche y tienes 2 opciones en éste momento:")
print("1) Volver a casa.")
print("2) Seguir fuera un par de horas más.")
opcion1 = input("Elige 1 o 2: ")

if opcion1 == "Volver a casa":
    print("Decides regresar a casa antes del anochecer, pero para tu desgracia, has sufrido un accidente, costandote la vida,")
    print("Despiertas en medio de la nada, al instante te das cuenta que has muerto...desgraciadamente,")
    print("Caminas por las calles estando totalmente perdido, nadie te puede ver, pero tú puedes ver algo que antes no,")
    print("Ciraturas de gran tamaño con máscaras parecidas a cráneos")
    print("Y uno de ellos se está enfrentando a una persona el cual sostiene una espada, vistiendo un atuendo oscuro y particular,")
    print("algo te dice que ésa persona no es humana...")
    print("La criatura perece ante ésa persona y luego voltea a verte, se da cuenta que eres un alma perdida el cual recientemente ha muerto,")
    print("No crees nada de lo que estás viendo, pero la persona no parece tener intenciones de lastimarte, más bien, quiere ayudarte")
    print("La persona te lleva al lugar dónde gente como él habita allí y ha conocido la muerte para llegar hasta allí,")
    print("Bienvenido a la Sociedad de almas, la persona te da indicaciones de todo resumidamente sobre éste lugar")
    print("y te da la recomendación de inscribirte a la academia de los Segadores de Almas")
    print("acá mismo, tienes dos opciones:")
    print("1) Inscribirte a la academia.")
    print("2) Descansar en paz.")
    opcion2 = input("Elige 1 o 2: ")
    
    if opcion2 == "Inscribirte en la Sociedad de Almas":
        print("Te inscribes a la academia de los Segadores de Almas, allí entrenas, aprendes y mejoras,")
        print("Mientras pasa el tiempo estando en la academia, ahora tienes lo necesario para ser un Segador de Almas")
        print("Te asignan en una de las divisiones (son como grupos) liderados por un capitán segador,")
        print("Ahora, tú como Segador de Almas, tienes la responsabilidad de llevarte a los muertos, matar a Hollows y defender a la Sociedad de Almas,")
        print("En éste momento, ya eres lo suficientemente fuerte como para lidiar con enemigos fuertes, por lo cual,")
        print("Tienes dos opciones:")
        print("1) Ir al mundo humano")
        print("2) Quedarte más tiempo")
        opcion3 = input("Elige 1 o 2: ")
        
        if opcion3 == "Ir al mundo humano":
            print("Abres un portal el cual te lleva directo al mundo humano para ver qué puedes hacer")
            print("Llegaste a tu país de orígen, muchas cosas han cambiado desde que has muerto, te da cierta nostalgia")
            print("Consigues un par de almas perdidas y los mandas a la Sociedad de Almas")
            print("Pasan las horas y decides enfrentar a Hollows, y cuando llegas a un sitio indicado para enfrentarlos, algo sucede,")
            print("Hay muchos restos de Hollows en el suelo, supones que un, o algunos Segadores de Almas ya se encargaron, pero...")
            print("En el fondo, vez una figura humanoide en las sombras devorando restos de Hollows, y nota tu presencia,")
            print("Te observa fijamente y sientes un gran peligro con tan solo verlo, pero antes de que te hayas dado cuenta, él ya iba por tí")
            print("Éso no era sólo un Hollow...era un Vasto Lorde.")
            print("Fin (Has muerto a manos de un Hollow en su última evolución).")
            
        else:
            print("Decides quedarte más tiempo en la Sociedad de Almas, después de todo, sientes que aún te quedan cosas por hacer,")
            print("Un día, decides entrenar con tu Zampakuto (que sería el arma de un Segador de Almas) entrando a tu mundo interior,")
            print("Ya tienes tu Shikai (primera transformación de tu Zampakuto), pero falta desbloquear tu Bankai, y por éso estás aquí,")
            print("El espíritu de tu Zampakuto te pone a prueba usando el poder del Bankai, un duelo arduo e intenso...")
            print("Pero al final vences y consigues tu Bankai, en éstos momentos ya eres un Segador de Almas fuerte,")
            print("Incluso podrías ascender a un capitán en la división que fuiste asignado...")
            print("Fin (Segaador de Almas).")
            
    else:
        print("Decides no inscribirte a la Academia de la sociedad de almas, por ende, lo único que te queda es descansar en la Sociedad de Almas")
        print("El destino te ha jugado una mala broma, ahora que te lo pones a pensar, incluso te preguntas:")
        print("¿Cómo se lo tomarán las personas que te conocen? ¿Qué se supone que tienes que hacer?")
        print("Son muchas preguntas, pero lo único que te queda por hacer es divagar por éste lugar...")
        print("Un día, la Sociedad de Almas ha detectado una invasión enemiga, tratándose de personas diferentes a los Segadores de Almas,")
        print("Estás cerca de ellos y no te sientes seguro, pero la curiosidad te urge de saber almenos cómo se ven")
        print("Tienes dos opcines: ")
        print("1) Asomarse")
        print("2) Alejarse")
        opcion3 = input("Elige 1 o 2: ")
        
        if opcion3 == "Asomarse":
            print("Fin. ")
            
        else:
            print("Fin.")
            
else:
    print("Decides quedarte fuera de casa hasta el anochecer, pero...sientes un mal presentimiento,")
    print("No hay nadie alrededor, nisiquiera un ser vivo, y cuando menos te lo esperas")
    print("Sientes que algo te devoró, algo más grande qur tú y nisiquiera lo has podido ver,")
    print("Abres los ojos y te sientes liviano, te ves transparente, no sientes nada,")
    print("Te has convertido en un alma perdida y desolada en medio de una calle vacía durante la noche...")
    print("Y no sólo éso, ahora eres capáz de ver monstruos ectraños de gran tamaño con máscaras queparecen cráneos en sus caras,")
    print("Posiblemente uno de ellos te devoró")
    print("Tienes una cadena conectado a un sello en tu pecho, sientes unas extrañas ganas de tirar de ella...")
    print("¿Qué decides hacer?:")
    print("1) Vagar por la ciudad e ignorar el impulso.")
    print("2) Tirar de la cadena.")
    opcion2 = input("Elige 1 o 2: ")
    
    if opcion2 == "Vagar por la ciudad e ignorar el impulso":
        print("No tiras de la cadena, pero ahora...¿Adónde se supone que tienes que ir?")
        print("Sigues vagando y un extraño hombre te encuentra, al parecer puede verte...")
        print("Aquel hombre, con su misteriosa aura, te hace la pregunta de querer unirte a él,")
        print("Pero, como dicen aquellas personas sabias de mayor edad")
        print("(en especial tus padres que de seguro te lo han dicho cuando eras niño), no debes confiar en extraños,")
        print("Sin embargo, no tienes nada que perder, después de todo, ya estás muerto,")
        print("Miras al misterioso hombre a los ojos pensando en qué responderle...")
        print("¿Cuál será tu respuesta?")
        print("1) Aceptar en unirte a él.")
        print("2) Rechazar la oferta.")
        opcion3 = input("Elige 1 o 2: ")
        
        if opcion3 == "Aceptar en unirte a él":
            print("Decides aceptar y el hombre te guía hacia un nuevo lugar para tí...")
            print("...Desde ése día, el hombre te ha convertido en un Fullbringer,")
            print("Te ha regresado a la vida y ahora tienes nuevas capacidades únicas,")
            print("Los restos de aquel monstruo que te mató, ahora son parte de tí")
            print("Y puedes usarlos a voluntad propia convirtiendolos en poderes,")
            print("Te sientes agradecido con aquel hombre extraño, pero ahora...")
            print("Te espera una bizarra aventura junto a un grupo que ha tenido una suerte similar a la tuya.")
            print("Fin (Fullbringer).")
            
        else:
            print("Decides no aceptar la oferta, pues no confías en ése hombre")
            print("Escuchas cómo el misterioso hombre suelta un suspiro ligero de desepción...pero él respetará tu decisón")
            print("Ese hombre se aleja de tí poco a poco, hasta que tú llegas a estar solo una vez más...")
            print("Y al final, sientes cómo una luz rodea tu cuerpo, te eleva y te lleva a otro lugar como si de un viaje en portal se tratase")
            print("Abres los ojos nuevamente y ahora te encuentras en un sitio donde las almas perdidas deben pertenecer...")
            print("Así es, ahora descanzarás en la Sociedad de Almas...")
            print("Fin (Lost Soul).")
            
    else:
        print("Decides dejarte llevar por el impulso, tomas la cadena con ambas manos y...")
        print("Empiezas a tirar, no una, ni dos si no hasta 5 veces hasta que finalmente")
        print("Te quitas el sello del pecho, sientes cómo vas perdiendo consciencia de tí mismo")
        print("Hasta que...te conviertes en una criatura de gran tamaño con una máscara parecida a un cráneo")
        print("Ya no recuerdas quién eres, simplemente eres un monstruo...un Hollow")
        print("Pasa el tiempo, te has dirigido al hogar de tu especie, Hueco Mundo.")
        print("Aquí, los Hollow son como animales, se rigen bajo la ley del más fuerte")
        print("Y tú, has tenido la suerte de evolucionar constantemente y sobrevivir a adversidades los cuales son más peligrosos que tú")
        print("Hasta que estás en el último paso de la evolución, pero te das cuenta de algo")
        print("Has descubierto que podrías quitarte la máscara, pero no sabes qué pasará si haces éso...")
        print("Tienes dos opciones:")
        print("1) Alcanzar la cima de la evolución Hollow.")
        print("2) Quitarte la máscara.")
        opcion3 = input("Elige 1 o 2: ")
        
        if opcion3 == "Alcanzar la cima de la evolución Hollow":
            print("Decides no quitarte la máscara y quedarte así como estás,")
            print("Luchas para sobrevivir y ser cada vez más fuerte en éste mundo lleno de criaturas idénticasa tí,")
            print("Hasta que...finalmente evolucionas, y ahora te has convertido en una bestia elcual sólo pocos se atreverían a desafiarte,")
            print("Rugidos intimidantes, fuerza irreal, velocidad aterradora, resistencia implacable, prácticamnete nada te podrá detener,")
            print("Bienvenido...a la cima dela evolución.")
            print("Fin (Vasto Lorde).")
            
        else:
            print("Te quitas la máscara con mucho esfuerzo, hasta que lo logras y sientes cómo cambias una vez más,")
            print("Hasta que, vas vuelto en tí mismo como eras antes, cuando estabas vivo, pero...")
            print("Tienes un agujero en tu pecho, indicando que aún eres uno de ellos,")
            print("rápidamentedecides abandonar Hueco Mundo y te diriges a un lugar más civilizado, donde hay gente como tú")
            print("Ése lugar se llama Las Noches, y a partir de aquí, te das cuenta que tu verdadero camino a la evolución Hollow, empieza aquí")
            print("Entrenas y te haces más fuerte, pero conel alivio de que ya no tendrás que preocuparte por la supervivencia de un Hollow")
            print("Y también al haber recuperado ésa humanidad el cual una vez has perdido.")
            print("Fin (Arrancar).")